const $=s=>document.querySelector(s);let token=sessionStorage.getItem('tvbox-token')||'';const notice=m=>$('#notice').textContent=m;
async function api(path,opt={}){opt.headers={...(opt.headers||{}),'Content-Type':'application/json; charset=UTF-8',...(token?{Authorization:'Bearer '+token}:{})};const r=await fetch(path,opt),d=await r.json().catch(()=>({message:'响应无效'}));if(!r.ok)throw new Error(d.message||d.error||'请求失败');return d}
function fillSettings(s={}){ $('#debug-open').checked=!!s.debugOpen;$('#parse-webview').checked=s.parseWebView!==false;$('#play-type').value=s.playType??2;$('#play-render').value=s.playRender??0;$('#play-scale').value=s.playScale??0;$('#doh-url').value=s.dohUrl??0;$('#home-rec').value=s.homeRec??0;$('#search-view').value=s.searchView??0 }
function readSettings(){return{debugOpen:$('#debug-open').checked,parseWebView:$('#parse-webview').checked,playType:Number($('#play-type').value),playRender:Number($('#play-render').value),playScale:Number($('#play-scale').value),dohUrl:Number($('#doh-url').value||0),homeRec:Number($('#home-rec').value),searchView:Number($('#search-view').value)}}
async function paired(){try{const d=await api('/api/v1/config');$('#config-url').value=d.url||'';fillSettings(d.settings);$('#pair-card').hidden=true;$('#console').hidden=false;$('#badge').textContent='已配对';$('#badge').classList.add('on');poll()}catch(e){token='';sessionStorage.removeItem('tvbox-token')}}
$('#pair-form').onsubmit=async e=>{e.preventDefault();try{const d=await api('/api/v1/pair',{method:'POST',body:JSON.stringify({code:$('#code').value})});token=d.token;sessionStorage.setItem('tvbox-token',token);notice('配对成功');setTimeout(()=>{if($('#notice').textContent==='配对成功')notice('')},2000);paired()}catch(e){notice(e.message)}};
$('#config-form').onsubmit=async e=>{e.preventDefault();try{notice((await api('/api/v1/config',{method:'PUT',body:JSON.stringify({url:$('#config-url').value,settings:readSettings()})})).message)}catch(e){notice(e.message)}};
$('#search-form').onsubmit=async e=>{e.preventDefault();try{await api('/api/v1/commands/search',{method:'POST',body:JSON.stringify({word:$('#search-word').value})});notice('已发送搜索')}catch(e){notice(e.message)}};
$('#play-form').onsubmit=async e=>{e.preventDefault();try{await api('/api/v1/quick-play',{method:'POST',body:JSON.stringify({url:$('#play-url').value,title:$('#play-title').value})});notice('已发送播放请求')}catch(e){notice(e.message)}};
document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>control(b.dataset.action,Number(b.dataset.value||0)));$('#seek').onchange=()=>control('seek',Number($('#seek').value));document.querySelectorAll('.tab').forEach(tab=>tab.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===tab));document.querySelectorAll('.panel').forEach(x=>x.classList.toggle('active',x.id==='tab-'+tab.dataset.tab));history.replaceState(null,'','#'+tab.dataset.tab)});
async function control(action,value=0){try{await api('/api/v1/playback',{method:'POST',body:JSON.stringify({action,value})})}catch(e){notice(e.message)}}function fmt(s){s=Math.max(0,Math.floor(s||0));return Math.floor(s/60)+':'+String(s%60).padStart(2,'0')}
async function poll(){try{const d=await api('/api/v1/playback');$('#state').textContent=d.available?(d.playing?'播放中':'已暂停'):'未连接播放器';$('#seek').max=Math.max(0,d.duration||0);if(document.activeElement!==$('#seek'))$('#seek').value=d.position||0;$('#time').textContent=fmt(d.position)+' / '+fmt(d.duration)}catch(e){if(e.message.includes('配对')){token='';sessionStorage.removeItem('tvbox-token');location.reload()}}setTimeout(poll,1000)}if(token)paired();
